# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b837ca534c63dc84e744ff1fda330bd51f939bd4c791a60c81e197176f78befc2457081b2ef6d7ced98f6bededb64fb9bc5e693097b90fa23872af2500001f2b

test:
  secret_key_base: 291cb4d850dff38d2ae033bb72be7be0c0464dd2d81217d6a8122d3b6587f171361869e4a4077a1e2b174d7395d227a197b92eee4e2a726a6d0dc288ae7ae680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
